version: '3.1'

services:
  app:
    image: 'exchange-rate-calculator:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update    
  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data
volumes:
  postgres_database:
    external: true
      